### ISSUE TITLE
bug: Capacitor-firebase + Capacitor-mlkit version conflicts

### ISSUE THREAD

**Issue by gerardopar** [capawesome-team/capacitor-mlkit#204] opened 2024-11-05 18:18 UTC
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

6.2.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

We are currently using the [capacitor-mlkit](https://github.com/capawesome-team/capacitor-mlkit) and [capacitor-firebase](https://github.com/capawesome-team/capacitor-firebase) plugins in our app.

With the following versions, everything works smoothly:

```json
"@capacitor-firebase/authentication": "^6.1.0",
"@capacitor-mlkit/barcode-scanning": "6.1.0",
"firebase": "^10.14.1"
```

However, we recently upgraded to the latest versions (`6.2.0`) to address an issue with Google login on iOS. After the update, versioning conflicts emerged between the plugins:

```json
"@capacitor-firebase/authentication": "^6.2.0",
"@capacitor-mlkit/barcode-scanning": "6.2.0",
"firebase": "^11.0.1"
```

### Error Details:

The issue stems from a version incompatibility with `GoogleUtilities/Environment`. Specifically:

- `FirebaseAuth` requires `GoogleUtilities/Environment` version 8.0 or above.
- `GoogleMLKit` depends on version 7.2.

This discrepancy causes CocoaPods to fail during installation. Here’s a screenshot of the error:

![Screenshot 2024-11-05 at 9 56 42 AM](https://github.com/user-attachments/assets/cce1b7b7-b547-4e38-9613-36f4cfc6b2f9)

Is there a recommended approach to resolve these conflicts, or are there planned updates to improve compatibility across these dependencies?

Thank you!

### Expected behavior

Expected version bumps to work as expected

### Reproduction

https://github.com

### Steps to reproduce

the following pkgs should cause the issue we are running into

"@capacitor-firebase/authentication": "^6.2.0",
"@capacitor-mlkit/barcode-scanning": "6.2.0",
"firebase": "^11.0.1",

### Capacitor doctor

```
run pnpm i 
run npx cap sync 
```

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-11-05 21:25
I close this as duplicate of https://github.com/capawesome-team/capacitor-firebase/issues/750

**Closed by robingenz** 2024-11-05 21:25 UTC
Labels: needs: triage, bug/fix
