### ISSUE TITLE
bug: QR code read from file on iOS

### ISSUE THREAD

**Issue by elzone** [capawesome-team/capacitor-mlkit#217] opened 2024-12-22 12:45 UTC
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

6.2.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

When try to read QR code from file on iOS device, get the blank result with such trace from Xcode terminal:

```
INFO: Initialized TensorFlow Lite runtime.
2024-10-10 23:36:53.464352+0400 App[14160:3222069] Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
⚡️  TO JS undefined
⚡️  To Native ->  FilePicker pickImages 34251905
2024-10-10 23:37:00.285120+0400 App[14160:3222069] [Assert] +[UIInputViewSetPlacementInvisible placementWithPlacement:]: Should not be called with an invisible placement
2024-10-10 23:37:00.585361+0400 App[14160:3222069] [Assert] +[UIInputViewSetPlacementInvisible placementWithPlacement:]: Should not be called with an invisible placement
2024-10-10 23:37:00.585568+0400 App[14160:3222069] [Assert] +[UIInputViewSetPlacementInvisible placementWithPlacement:]: Should not be called with an invisible placement
2024-10-10 23:37:00.585591+0400 App[14160:3222069] [Assert] +[UIInputViewSetPlacementInvisible placementWithPlacement:]: Should not be called with an invisible placement
2024-10-10 23:37:00.585619+0400 App[14160:3222069] [Assert] +[UIInputViewSetPlacementInvisible placementWithPlacement:]: Should not be called with an invisible placement
⚡️  TO JS {"files":[{"path":"file:\/\/\/var\/mobile\/Containers\/Data\/Application\/948ACED3-E3BC-4BC9-B7D1-FC2F1B33B0E1\/Library\/Caches\/8F35E02D-CCD7-4C96-B961-9D693CEB89DA\/IMG_5892.png","modifiedAt":1728317065793,"height":2436,"name":"IMG_5892.png","size":67321
⚡️  To Native ->  BarcodeScanner readBarcodesFromImage 34251906
2024-10-10 23:37:01.358173+0400 App[14160:3222314] [Unknown process name] 
CGBitmapContextCreate: unsupported parameter combination:
	Gray | 16 bits/component, integer | 1125 bytes/row.
	kCGImageAlphaNone | kCGImageByteOrderDefault | kCGImagePixelFormatPacked
Set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see more details.
2024-10-10 23:37:01.358252+0400 App[14160:3222314] [Unknown process name] CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
2024-10-10 23:37:01.358282+0400 App[14160:3222314] [Unknown process name] CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
2024-10-10 23:37:01.358307+0400 App[14160:3222314] [Unknown process name] CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
⚡️  TO JS {"barcodes":[]}
```

### Expected behavior

When read QR code from file on iOS should return QR code data.

### Reproduction

https://github.com/elzone/qr-code-issue

### Steps to reproduce

1. Prepare app for iOS from sources (github link)
2. Run the app on iOS device (from 16.0 iOS version)
3. Press the button on the screen
4. Select file with QR code
5. In Xcode terminal check the message from plugin (see Current behavior section)

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/core: 6.2.0
  @capacitor/cli: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

[success] iOS looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by elzone** [comment] 2024-12-23 07:08
Hi Robin,
Sorry i can't check the minimal app on iOS, cause don't have certificate and provision files. how can i do this before send the minimal repo to you?

i prepared my own repo (please check this link - https://github.com/elzone/qr-code-issue). is it not enough for test/debug?

**Comment by robingenz** [comment] 2024-12-23 07:27
> i prepared my own repo (please check this link - elzone/qr-code-issue). is it not enough for test/debug?

This is not a **minimal**, reproducible example. There are a lot of dependencies that are not needed. I'm also not familiar with React.

**Comment by elzone** [comment] 2024-12-23 07:43
hi Robin,
here is the repo:
https://github.com/elzone/barcode-reader-ios-issue-read-from-file

**Comment by robingenz** [comment] 2024-12-23 07:56
Which image can I use to reproduce this?

**Comment by elzone** [comment] 2024-12-23 08:01
please try these
![photo_2024-12-23 12 00 43](https://github.com/user-attachments/assets/973d2bc9-0dd0-465f-8086-4a58e087da2a)
![photo_2024-12-23 12 00 33](https://github.com/user-attachments/assets/a94a7f97-5372-4ed8-be3c-1c5abf0ab47e)

**Comment by robingenz** [comment] 2024-12-25 08:08
Unfortunately, I cannot reproduce your issue.

https://github.com/user-attachments/assets/d6b0a46f-4fce-4825-8741-16fba1d365a2

The example works without problems (I've just replaced `console.log` with `alert`).

**Comment by elzone** [comment] 2024-12-25 10:10
hi Robin,
can you tell me which iOS version and device do you use?

**Comment by elzone** [comment] 2024-12-25 10:20
and what about this error (in my case):

`2024-10-10 23:37:01.358173+0400 App[14160:3222314] [Unknown process name] 
CGBitmapContextCreate: unsupported parameter combination:
	Gray | 16 bits/component, integer | 1125 bytes/row.
	kCGImageAlphaNone | kCGImageByteOrderDefault | kCGImagePixelFormatPacked
Set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see more details.`

**Comment by robingenz** [comment] 2024-12-25 13:21
iPhone 13 with iOS 18.1.1. I've only tested the first image.

**Comment by elzone** [comment] 2024-12-25 13:51
can you check the second one too, please?

**Comment by robingenz** [comment] 2024-12-25 19:06
The second one also works.
![IMG_4247](https://github.com/user-attachments/assets/f8b502fc-2afd-49ba-9669-1584f88a84bd)

**Comment by elzone** [comment] 2024-12-25 19:43
Hm, interesting
On my device (iPhone X with iOS 16.7.10) both images show the issue.

As i understand - here we don't need any specific iOS permissions, right?

**Comment by robingenz** [comment] 2024-12-25 19:50
No, you don't need any specific permissions.

**Comment by elzone** [comment] 2024-12-25 20:01
i see.
will try to check on other devices (model and os version)
will put results here

**Comment by elzone** [comment] 2024-12-26 15:40
For other devices (with iOS 18.1 for example) - for some images with QR codes all ok, but not for all.
Not clear for me the reason why

**Comment by robingenz** [comment] 2024-12-26 15:48
This seems to be a problem with the ML Kit SDK and not with the plugin. Maybe create an issue in https://github.com/googlesamples/mlkit. The issue must be reproducible in any case, otherwise it's hard to help you. I will close this issue for now.

**Closed by robingenz** 2024-12-26 15:48 UTC
Labels: needs: triage, platform: ios, needs: reproduction, bug/fix, package: barcode-scanning

**Comment by aliyafthh** [comment] 2025-01-08 03:13
@elzone Did you manage to find a fix for this? I am also facing the same issue of receiving blank result from barcode reader for both QR and barcodes but only in iOS 16. iOS 18 is okay for me

**Comment by elzone** [comment] 2025-01-09 09:16
hi. no. as Robin mentioned, this error mostly depend on mlkit. have to add bug report there
