### ISSUE TITLE
bug: Can't read an Aztec code

### ISSUE THREAD

**Issue by scr2em** [capawesome-team/capacitor-mlkit#164] opened 2024-06-29 12:39 UTC
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

6.1.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

It can't read this code while the old plugic could 
![image](https://github.com/capawesome-team/capacitor-mlkit/assets/4671486/89030cc4-e1d7-4697-b399-102b14ce4745)

### Expected behavior

I migrated from @capacitor-community/barcode-scanner and expected it work the same

### Reproduction

use your demo app 

### Steps to reproduce

1. use your demo app
2. scan the attached barcode 

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-06-29 13:08
I cannot reproduce your issue (see video). I am therefore closing this issue.

https://github.com/capawesome-team/capacitor-mlkit/assets/13857929/4635a7ac-edd9-4367-bf49-1c676e5385b5

**Closed by robingenz** 2024-06-29 13:08 UTC
Labels: needs: triage, platform: ios, bug/fix, package: barcode-scanning

**Comment by scr2em** [comment] 2024-06-29 13:12
@robingenz Yep, it was my fault. I was checking if `.rawValue` exists or not. but now I'm always getting the barcode from converting the bytes array. 
<img width="1004" alt="image" src="https://github.com/capawesome-team/capacitor-mlkit/assets/4671486/8503b8e1-1283-4218-a896-ba61900b748c">


```js
const barcode = barcodeScannedEvent.barcode.bytes.map((byte) => String.fromCharCode(byte)).join("");
```

in case someone had the same issue
