### ISSUE TITLE
bug: Code39 scan results are incorrect

### ISSUE THREAD

**Issue by h3786010** [capawesome-team/capacitor-mlkit#93] opened 2023-11-07 07:49 UTC
### Plugin(s)

- [x] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Code39 Almost every scan results are different

### Expected behavior

Code39 correct scan results

### Reproduction

N/A

### Steps to reproduce

N/A

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1

[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-11-24 12:58
I close this issue as duplicate of #96.

**Closed by robingenz** 2023-11-24 12:58 UTC
Labels: needs: triage, platform: android, needs: reply, needs: reproduction, bug/fix, package: barcode-scanning
