### ISSUE TITLE
bug: PreviewView is null on Android Device

### ISSUE THREAD

**Issue by masosky** [capawesome-team/capacitor-mlkit#53] opened 2023-06-26 17:54 UTC
### Plugin(s)

- [X] Barcode Scanning
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When i execute the method `startScan` I have an issue on the Android Code
`previewView = plugin.getActivity().findViewById(R.id.preview_view);`

previewView is null so next line fails

`preview.setSurfaceProvider(previewView.getSurfaceProvider());`

This was working week ago

### Expected behavior

`startScan` works and I do not see a black screen

### Reproduction

No reproduction code

### Steps to reproduce

1. Use startScan on Android (Xiaomi Redmi Note 11)

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/core: 5.0.5
  @capacitor/cli: 5.0.5
  @capacitor/ios: 5.0.5
  @capacitor/android: 5.0.5

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-06-27 13:16
Thank you for your request.

Does this error also occur with the [ML Kit Demo App](https://github.com/robingenz/capacitor-mlkit-plugin-demo)?

**Comment by masosky** [comment] 2023-06-27 13:47
I have tested this Demo Kit and works well.
I suspect it is a dependencies problem

**Comment by robingenz** [comment] 2023-06-27 13:52
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by masosky** [comment] 2023-06-27 18:06
Code: https://github.com/masosky/capacitor-app-barcode-bug
Can only run on Android due to Barcode Scanner cannot run on Web

How to reproduce

1. `yarn`
2. `yarn build:android`
3. Run the generated code on device (Android)

**Comment by robingenz** [comment] 2023-06-27 18:58
Thanks for the example. As far as I can see this is not a minimal example or are all the dependencies necessary (e.g. `@capacitor-community/apple-sign-in` or React)?
Please create a minimal, reproducible example with [this template](https://github.com/capawesome-team/.capacitor-app) and only the dependencies/changes that are necessary for reproduction. This is the fastest way to help you, as my time is limited.

**Comment by masosky** [comment] 2023-06-27 19:47
I found the issue. Ionic is installing exactly `@capacitor-community/apple-sign-in` on Android and Ios.
In order to exclude. You must only include the plugins you need on the capacitor.config.json
`"android": {
    "includePlugins": [
      "@capacitor-firebase/authentication",
      "@capacitor-mlkit/barcode-scanning",
      "@capacitor/app",
      "@capacitor/camera",
      "@capacitor/haptics",
      "@capacitor/keyboard",
      "@capacitor/splash-screen",
      "@capacitor/status-bar"
    ]
  }`

**Comment by robingenz** [comment] 2023-06-28 10:32
I don't really understand what you mean. Have you found the problem and can I close the issue?

**Comment by masosky** [comment] 2023-06-28 12:44
I could solve the issue yes. Sorry for my bad explanation.
This library `@capacitor-community/apple-sign-in` was installed on Android and it should not be there. So I excluded it.
Now it works on Android. It was a library conflict.
Thanks

**Comment by robingenz** [comment] 2023-06-28 12:51
Alright, i am glad it works now.

**Closed by robingenz** 2023-06-28 12:51 UTC
Labels: needs: triage, platform: android, needs: reproduction, bug/fix, package: barcode-scanning

**Comment by udaycodealchemy** [comment] 2023-08-16 10:24
assasdasd

**Comment by rdlabo** [comment] 2023-09-23 08:15
OK, I found the reason for this. It was not a problem with @capacitor-community/apple-sign-in, but with the order of plugins written to `android/app/capacitor.build.gradle` . It must always be `capacitor-mlkit-barcode-scanning` first.

OK:
```
 apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"
 dependencies {
    implementation project(':capacitor-mlkit-barcode-scanning')
    implementation project(':capacitor-community-facebook-login')
    implementation project(':capacitor-community-firebase-analytics')
```

NG:
```
 apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"
 dependencies {
    implementation project(':capacitor-community-facebook-login')
    implementation project(':capacitor-mlkit-barcode-scanning')
    implementation project(':capacitor-community-firebase-analytics')
```

To specify this order, use includePlugins in capacitor.config.json.

**Comment by robingenz** [comment] 2023-09-24 10:17
@rdlabo Thanks for sharing!
