### ISSUE TITLE
bug: Barcode Scanner Sometimes Reads Incorrect Values for Code128 Barcode

### ISSUE THREAD

**Issue by umeshsarkar** [capawesome-team/capacitor-mlkit#171] opened 2024-07-24 14:58 UTC
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

6.1.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When scanning a Code128 barcode, the scanner does not always return the correct value. For instance, as shown in the attached screenshots, I am trying to scan a Code128 barcode with the accurate value `8003012345678902345678901234`. However, it returns `8243175366890234567580173`, which is incorrect.

- The incorrect return code may vary between scans.
- The issue occurs frequently but not consistently on every scan.

![scanning-barcode-real](https://github.com/user-attachments/assets/a4b4bd25-328e-4382-a86b-22e6e7d31c04) ![scan-result-with-wrong-value](https://github.com/user-attachments/assets/535509da-4512-465c-98e6-a3f23e931c07)

### Expected behavior

The barcode scanner should return the actual value of the Code128 barcode on every scan.

### Reproduction

https://github.com/robingenz/capacitor-mlkit-plugin-demo

### Steps to reproduce

1. Clone the official barcode-scanning demo repository:
```
git clone https://github.com/robingenz/capacitor-mlkit-plugin-demo.git
```
2. Change to the root directory of the project:
```
cd capacitor-mlkit-plugin-demo
```
3. Install all dependencies:
```
npm i
```
4. Prepare and launch the Android app:
```
npx ionic cap sync android
npx ionic cap run android
```
5. Select the barcode scanning module in the app.
6. In the barcode scanning module, select the format `Code128` and click on `START SCAN`.
7. Scan the barcode from the attached Code128 barcode sample.
8. After a successful scan, the result values are displayed at the bottom of the barcode scanning page.
9. Compare the Raw Value or Display Value to the value mentioned in the attached Code128 barcode sample. They do not match.

- Note: The incorrect return code may vary.
- The issue is frequent but not consistent on every scan.

[sample-barcode-code128.pdf](https://github.com/user-attachments/files/16362109/sample-barcode-code128.pdf)

### Other information

The device used for testing: Google Pixel 6a (Android Version 14)

### Capacitor doctor

  💊 Capacitor Doctor 💊

Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/android: 6.0.0
  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0

[success] Android looking great! 👌
[error] Xcode is not installed

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-07-25 07:04
I close this issue as duplicate of #96.

**Closed by robingenz** 2024-07-25 07:04 UTC
Labels: needs: triage, bug/fix
