### ISSUE TITLE
bug(barcode-scanning): `NullPointerException` during `startScan(...)`

### ISSUE THREAD

**Issue by MohMehrnia** [capawesome-team/capacitor-mlkit#107] opened 2023-12-12 10:51 UTC
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

5.3.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

I have a vue .js app (vue.js 2.0) and add barcode reader package but when start scan show me bellow error

startScan failed.
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.camera.view.PreviewView.setScaleType(androidx.camera.view.PreviewView$ScaleType)' on a null object reference
at io.capawesome.capacitorjs.plugins.mlkit.barcodescanning.BarcodeScanner.lambda$startScan$0(BarcodeScanner.java:108)
at io.capawesome.capacitorjs.plugins.mlkit.barcodescanning.BarcodeScanner.$r8$lambda$XoJ4tltbmXkBZjUvzn_RkQLTSis(Unknown Source:0)
at io.capawesome.capacitorjs.plugins.mlkit.barcodescanning.BarcodeScanner$$ExternalSyntheticLambda3.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8437)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:560)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### Expected behavior

Start Scanning

### Reproduction

capawesome-team/.capacitor-app.

### Steps to reproduce

1. install on vue.js app
2. copy all sample code for scanning
3. sync (npx cap sync android)
4. open (npx cap open android)
5. debug (on android platform)
6. show erorr

### Capacitor doctor

[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: unknown
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1

[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by Imeguras** [comment] 2024-01-14 23:46
sorry to necrobump but im having the same issue on vue3, tried to add permissions and it even warned me of missing 
<uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
git url is https://github.com/Imeguras/gora_pickerv2_FrontEnd

A vue based tutorial would be nice

**Comment by robingenz** [comment] 2024-01-15 07:32
Please provide a **Minimal**, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by Imeguras** [comment] 2024-01-15 15:13
> Please provide a **Minimal**, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

https://github.com/Imeguras/minimalVue
i've made this but now its giving me a new error

Uncaught (in promise) Error: The Google Barcode Scanner Module is not available. You must install it first.

**Comment by Imeguras** [comment] 2024-01-15 15:14
> > Please provide a **Minimal**, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.
> 
> https://github.com/Imeguras/minimalVue i've made this but now its giving me a new error
> 
> Uncaught (in promise) Error: The Google Barcode Scanner Module is not available. You must install it first.

ill atempt to fix it first

**Comment by Imeguras** [comment] 2024-01-15 15:53
> > > Please provide a **Minimal**, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.
> > 
> > 
> > https://github.com/Imeguras/minimalVue i've made this but now its giving me a new error
> > Uncaught (in promise) Error: The Google Barcode Scanner Module is not available. You must install it first.
> 
> ill atempt to fix it first

Welp somehow i made it work? I've placed omited some minor steps althouth they were repetitive and tipically just "build" orders, ill try to fix my version and post any results here

**Comment by Imeguras** [comment] 2024-01-15 16:44
welp i somehow fixed it in my main repo,
implementation "com.google.android.gms:play-services-code-scanner:16.1.0"
the above seems to have something to do with it, i also had to sync 
it can also be the styles present in the default blank format

**Comment by robingenz** [comment] 2024-01-15 16:46
@Imeguras Can you share the commit that fixed it?

**Comment by Imeguras** [comment] 2024-01-15 17:02
https://github.com/Imeguras/minimalVue/commit/21d377e5aff546477174248c8a68f1a113488538
this one 
my best guess its something related to placing 

> implementation "com.google.android.gms:play-services-code-scanner:16.1.0"
in the (build.graddle?) file

It fixed both minimal repo and the more complex project i was doing, however very different errors were presented in both one complained about missing some google bar reader library while the other was exactly equal to the one on the OP's post

**Comment by robingenz** [comment] 2024-01-15 22:22
> my best guess its something related to placing 
> 
> > implementation "com.google.android.gms:play-services-code-scanner:16.1.0"
> in the (build.graddle?) file

No, it shouldn't have anything to do with that. 🤔 I'm glad it's working for you now.

**Comment by atoui-zahreddine** [comment] 2024-03-07 16:07
I had the same issue. I fixed it by enabling data binding in the `build.gradle` of `@capacitor-mlkit/barcode-scanning`:

```gradle
buildFeatures {
  dataBinding true
}
dataBinding {
  enabled = true
}
```
When debugging the issue, I found that [previewView](https://github.com/capawesome-team/capacitor-mlkit/blob/3f55a650148a1fcdc2873abd9a632272a75824d3/packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScanner.java#L105) is always null, which means it didn't detect the view or something like that (sorry, I'm not that familiar with how native Android apps are built). After enabling data binding, the issue is gone.

New build.gradle:

```gradle
ext {
    junitVersion = project.hasProperty('junitVersion') ? rootProject.ext.junitVersion : '4.13.2'
    androidxAppCompatVersion = project.hasProperty('androidxAppCompatVersion') ? rootProject.ext.androidxAppCompatVersion : '1.6.1'
    androidxJunitVersion = project.hasProperty('androidxJunitVersion') ? rootProject.ext.androidxJunitVersion : '1.1.5'
    androidxEspressoCoreVersion = project.hasProperty('androidxEspressoCoreVersion') ? rootProject.ext.androidxEspressoCoreVersion : '3.5.1'
    androidxCameraCamera2Version = project.hasProperty('androidxCameraCamera2Version') ? rootProject.ext.androidxCameraCamera2Version : '1.1.0'
    androidxCameraCoreVersion = project.hasProperty('androidxCameraCoreVersion') ? rootProject.ext.androidxCameraCoreVersion : '1.1.0'
    androidxCameraLifecycleVersion = project.hasProperty('androidxCameraLifecycleVersion') ? rootProject.ext.androidxCameraLifecycleVersion : '1.1.0'
    androidxCameraViewVersion = project.hasProperty('androidxCameraViewVersion') ? rootProject.ext.androidxCameraViewVersion : '1.1.0'
    mlkitBarcodeScanningVersion = project.hasProperty('mlkitBarcodeScanningVersion') ? rootProject.ext.mlkitBarcodeScanningVersion : '17.1.0'
    playServicesCodeScannerVersion = project.hasProperty('playServicesCodeScannerVersion') ? rootProject.ext.playServicesCodeScannerVersion : '16.0.0'
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.0'
    }
}

apply plugin: 'com.android.library'

android {
    namespace "io.capawesome.capacitorjs.plugins.mlkit.barcodescanning"
    compileSdkVersion project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 33
    defaultConfig {
        minSdkVersion project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 22
        targetSdkVersion project.hasProperty('targetSdkVersion') ? rootProject.ext.targetSdkVersion : 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        dataBinding true
    }
    dataBinding {
        enabled = true
    }
}

repositories {
    google()
    mavenCentral()
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':capacitor-android')
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation "androidx.camera:camera-camera2:$androidxCameraCamera2Version"
    implementation "androidx.camera:camera-core:$androidxCameraCoreVersion"
    implementation "androidx.camera:camera-lifecycle:$androidxCameraLifecycleVersion"
    implementation "androidx.camera:camera-view:$androidxCameraViewVersion"
    implementation "com.google.mlkit:barcode-scanning:$mlkitBarcodeScanningVersion"
    implementation "com.google.android.gms:play-services-code-scanner:$playServicesCodeScannerVersion"
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
}
```

**Comment by robingenz** [comment] 2024-03-08 08:22
@atoui-zahreddine That's strange. It doesn't work for me. Have you changed anything else?

![grafik](https://github.com/capawesome-team/capacitor-mlkit/assets/13857929/aec72810-8184-497d-a199-e73fe08ead7d)

Btw: I can now reproduce the issue by simply installing the `@capacitor-community/apple-sign-in` plugin.

**Comment by atoui-zahreddine** [comment] 2024-03-15 14:09
from what I can see, data binding should be enable on the demo repository and on the plugin level.

adding :
```gradle
buildFeatures {
        dataBinding true
    }
    dataBinding {
        enabled = true
    }
``` 
In demo-repo/android/app/build.gradle and @capacitor-mlkit/barcode-scanning/android/build.gradle should fix the issue ( it did for me) .

I think there should be a better way to do this, I'll try to find an alternative to this.

**Comment by robingenz** [comment] 2024-03-18 08:46
@atoui-zahreddine Thank you for the update. That worked for me.

**Comment by robingenz** [comment] 2024-03-18 15:43
@atoui-zahreddine Yes, here you can find information on [how to get paid](https://capawesome.io/contributing/bounties/claim-a-bounty/#how-do-i-get-paid). Thank you again for taking a look!

Closed by #138

**Closed by robingenz** 2024-03-18 15:43 UTC
Labels: platform: android, bug/fix, package: barcode-scanning, bounty, $50

**Comment by atoui-zahreddine** [comment] 2024-03-18 22:59
@robingenz  Thank you! 
looking forward for more contribution. 
 
expense link : https://opencollective.com/capawesome/expenses/193657

**Comment by robingenz** [comment] 2024-03-19 06:03
@atoui-zahreddine Thanks. I've just approved your expense.

**Comment by robingenz** [comment] 2025-01-17 11:49
I think I've finally found a better solution to this problem: https://github.com/capawesome-team/capacitor-mlkit/pull/227 The preview view is now created dynamically. This means that a static layout is no longer necessary.

It will be part of the next release. If you have any problems, just let me know and create a new issue.
