### ISSUE TITLE
bug: cannot scan with phone facing an angle of 30-45 degrees (iOS)

### ISSUE THREAD

**Issue by nicolasmohamed** [capawesome-team/capacitor-mlkit#101] opened 2023-11-24 14:12 UTC
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

plugin does not scan a QR code when the phone is facing an angle of 30-45 degrees (previous plugin from capacitor worked OK)

### Expected behavior

plugin scans correctly with the phone facing an angle of 30-45 degrees 

### Reproduction

Happens with any project/code 

### Steps to reproduce

1. Open the plugin
2. Put the phone in an angle like between 30 and 45 degrees
3. Try to scan a QR code

### Other information

It happens with any project/code. We find it very odd that no one has reported it yet.

### Capacitor doctor

-

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-11-24 16:44
Please share an image for testing (I'm not sure if I'm allowed to post the picture from your email here).

**Comment by nicolasmohamed** [comment] 2023-11-25 08:40
![qr_facing_angle](https://github.com/capawesome-team/capacitor-mlkit/assets/30346948/2702118c-cc3b-40b5-911a-bb4f8a871e74)
Here's an example. Thanks.

**Comment by robingenz** [comment] 2023-11-28 08:42
I can reproduce your issue with my [demo app](https://github.com/robingenz/capacitor-mlkit-plugin-demo).

However, the problem does not seem to be the angle, but the QR code itself. It works for me with a different QR code at this angle. The problem should not be with the plugin but with the ML Kit Library. It does not recognize QR codes on this image. I have tried both with the camera and via FilePicker.

I am therefore closing this issue for the time being and recommend creating an issue in https://github.com/googlesamples/mlkit. Feel free to keep me up to date and link this issue.

**Closed by robingenz** 2023-11-28 08:42 UTC
Labels: platform: ios, bug/fix, package: barcode-scanning

**Comment by nicolasmohamed** [comment] 2023-11-28 18:12
Ok Robin, will do. Just for the record, it was working OK with zxing implementation. We'll compile a legacy app. Cannot believe I'm writing this in nov-2023 but I understand it has nothing to do with this plugin. Thanks.
