### ISSUE TITLE
bug: Can't see camera preview.

### ISSUE THREAD

**Issue by smaddionadv** [capawesome-team/capacitor-mlkit#197] opened 2024-10-09 09:33 UTC
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

6.1.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

- I trigger the scanning
- Scanning successfully starts
- The camera preview is not present
- If i put the phone in front of a qr code it scans correctly
- The value returned is correct

### Expected behavior

- I trigger the scanning
- The camera preview is visible
- The scan i successful

### Reproduction

-

### Steps to reproduce

-

### Other information

Can't share the complete code as is a work related project but if needed i can share specific parts if needed for debugging this issue

The project started as a React + Vite + TS then i added capacitor because the specs changed mid development.
Adding capacitor was successful and the app works great

I just can't see the camera preview
Tried all the steps mentioned in the docs, even the css rules but still the camera isn't shown.

This project uses [TailwindCSS](https://tailwindcss.com/) and [NextUI](https://nextui.org/)
Theres no IONIC stuff in this.

In the now deprecated capacitor/barcode-scanner GHRepo it was mentioned something about dark mode bugging the interface, so i obviously tried without dark mode and nothing changes.

As previously mentioned, the scanner , scans perfectly.

If more context or stuff is needed i will gladly provide it.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2

[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-10-09 10:43
This is most likely a bug in your implementation and not a bug in the plugin. I have just tested the latest version and everything worked without any problems. For this reason, I am closing this issue. Feel free to [create a discussion](https://github.com/capawesome-team/capacitor-mlkit/discussions/new/choose) or [book a consulting hour](https://polar.sh/capawesome-team/products/1c197541-e627-47b9-8c2c-7e4f41e8ea75).

**Closed by robingenz** 2024-10-09 10:43 UTC
Labels: needs: triage, platform: android, bug/fix, package: barcode-scanning
