### ISSUE TITLE
bug: Issues on Android when using biometric plugin and photo viewer

### ISSUE THREAD

**Issue by TheCorbin** [capawesome-team/capacitor-mlkit#141] opened 2024-03-25 18:40 UTC
### Plugin(s)

- [ x] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

5.4.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

On Android when opening the scanner we get a black screen as well as this error:

Msg: ERROR Error: Attempt to invoke virtual method 'void androidx.camera.view.PreviewView.setScaleType(androidx.camera.view.PreviewView$ScaleType)' on a null object reference

If the biometric plugin is placed in package.json after the barcode scanner the scanner works but if the Capacitor Photo Viewer is anywhere it will produce the error regardless of location.

![Screenshot 2024-03-25 at 1 31 40 PM](https://github.com/capawesome-team/capacitor-mlkit/assets/8755947/c8101519-78b3-4632-b09d-741ad61ecfd3)

I've created sample application here: https://github.com/TheCorbin/barcode-scanner-angular

### Expected behavior

From an Android device I would like to open the barcode scanner and see the camera view, as on iOS.

### Reproduction

https://github.com/TheCorbin/barcode-scanner-angular

### Steps to reproduce

1. Install both Biometric scanner (https://github.com/epicshaggy/capacitor-native-biometric) and Barcode Scanner.  This also works with capacitor photoviewer: https://github.com/capacitor-community/photoviewer

2. Implement a barcode scanner in the app.  Open and see a black screen.  Error about setscale on the Ionic logcat.

### Capacitor doctor

> npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-03-25 18:54
I close this as duplicate of #107. The fix will be published with v6.0.0. You can [patch the package](https://capawesome.io/blog/how-to-patch-a-capacitor-plugin/) while waiting for the release.

**Closed by robingenz** 2024-03-25 18:54 UTC
Labels: needs: triage, bug/fix

**Comment by TheCorbin** [comment] 2024-03-25 20:32
Thanks @robingenz Do you have a hypothetical timeline on that release?  

I added this to my android/app build gradle and the package android build gradle and still no result:

buildFeatures {
        dataBinding true
    }
    dataBinding {
        enabled = true
    }

**Comment by robingenz** [comment] 2024-03-25 21:16
I will publish v6.0.0 as soon as Capacitor 6 is available.
